#!/usr/bin/bash
# I love linux and i hate windows
path="$(dirname "$(readlink -f "$0")")"
if ( [ -z $(ls -aF |grep .db) ] )
then
mkdir .db
cd .db
else
cd .db
fi
select com in "Create database" "List databases" "Remove database" "Connect to database" "exit"
do
case $REPLY in 
1)
read -p "enter database name to be created " databse_name
case `"$path"/validation/db_naming_constraint $databse_name` in
"0" )
echo "database name shouldn't start with numbers"
;;
"1" )
echo "database name shouldn't contain special characters"
;;
"2" )
"$path"/"menu commands"/create_db `echo $databse_name|tr " " "_"`;
;;
"3" )
echo "database name shouldn't be empty";
;;
esac
;;
2)
"$path"/"menu commands"/ls_db;
;;
3)
read -p "enter database name to be removed " databse_name
case `"$path"/validation/db_naming_constraint $databse_name` in
"0" )
echo "database name shouldn't start with numbers"
;;
"1" )
echo "database name shouldn't contain special characters"
;;
"2" )
"$path"/"menu commands"/rm_db `echo $databse_name|tr " " "_"`;
;;
"3" )
echo "database name shouldn't be empty";
;;
esac
;;
4)
read -p "enter database name connect to " databse_name
source "$path"/"menu commands"/connect_db `echo $databse_name|tr " " "_"`;
;;
5)
break;
;;
*)
echo "$REPLY is invalid selection number";
;;
esac
done
