#!/usr/bin/bash
if [ -d "$1" ]
then 
cd "$1";
if [[ ${1:0:1} = '_' ]]
then
result=`echo $1|tr "_" " "`;
PS3="_${1:1}>>"
fi
<<alaa
select action in "create table" "drop table" "list table" "select from table" "update table" "delete table" "insert into table"
do
done
alaa
else
echo "`echo $1|tr "_" " "` database is not exist";
fi
