#!/usr/bin/bash
if [[ `ls -aF |grep /|tr "/" " " |grep "$1 "` = "$1 "  ]]
then 
rm -r "$1"
echo "`echo $1|tr "_" " " ` database is removed successfully";
else
echo "`echo $1|tr "_" " " `  database is not exist";
fi
