#!/usr/bin/bash
if [[ `ls -aF |grep /|tr "/" " " |grep "$1 "` = "$1 "  ]]
then 
rm -r "$1"
if [[ ${1:0:1} = '_' ]]
then
result=`echo $1|tr "_" " "`;
echo "_${result:1} database removed successfully";
else
echo "`echo $1|tr "_" " "` database removed successfully";
fi
else
echo "`echo $1|tr "_" " " `  database is not exist";
fi
