#!/usr/bin/bash
shopt -s extglob
chech_DB_naming () {
if [ -z $1 ]
then
result=3;
elif [[ $1 =~ ^[0-9] ]];
then 
result=0;
elif [[ $1 =~ ^[A-Za-z_]+ ]] && [[ $1 =~ ^[A-Za-z_0-9]*$ ]];
then
result=2;
else
result=1;
fi
}
chech_DB_naming $1
echo $result
